version: '3'

services:

  theInternetApp:
    image: gprestes/the-internet
    ports:
      - 7080:5000

  seleniumHub:
    image: selenium/hub
    depends_on:
      - theInternetApp
    ports:
      - 4444:4444
    environment:
      GRID_MAX_SESSION: 4
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIMEOUT: 300

  firefoxNode:
    image: selenium/node-firefox
    depends_on:
      - seleniumHub
    environment:
      HUB_PORT_4444_TCP_ADDR: seleniumHub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1
